### ISSUE TITLE
无法使用树莓派的RPi.GPIO库

### ISSUE THREAD

**Issue by Wisgon** [chainsx/ubuntu64-rpi#13]
我用pip安装的：$sudo pip install RPi.GPIO (版本是0.6.3)
然后，启动python，尝试：>>>import RPi.GPIO
得到错误提示：This module can only be run on a Raspberry Pi

**Comment by chainsx** [comment]
恩，这是因为64位系统没有引入64位RPi.GPIO的原因

**Comment by chainsx** [comment]
我会尽快添加对于64位RPi.GPIO的支持，
但是，你可能要等一段时间，请理解。

**Comment by Wisgon** [comment]
好的，没问题，辛苦你了
