### ISSUE TITLE
关于Wiringpi

### ISSUE THREAD

**Issue by Caper911** [chainsx/ubuntu64-rpi#14]
Wiringpi 这个库可以在64位系统上使用吗？

**Comment by lmxx1234567** [comment]
wiringpi 不能直接在64位下运行，需要使用源码编译，同时64位内核的问题导致/proc/cpuinfo 中没有hardware信息 https://github.com/raspberrypi/linux/issues/2110。不过修改wiringpi的源码应该可以让wiringpi正常运行，目前也有人给wiringpi提了issue。

**Comment by chainsx** [comment]
现在cpuinfo的问题已经解决了，直接加的BCM2837但是具体验证还没有试过

**Comment by lmxx1234567** [comment]
https://github.com/raspberrypi/linux/issues/2110#issuecomment-467827060
It works.
