### ISSUE TITLE
树莓派3B+ 的版本找不到网卡

### ISSUE THREAD

**Issue by aiminickwong** [chainsx/ubuntu64-rpi#16]
树莓派3B+ 的版本 安装ubuntu-18.04-aarch64-raspi3b-raspi3b-plus-20180501-devel-chainsx 无法使用有线网络，找不到网卡

**Comment by 12101111** [comment]
`sudo ifconfig eth0 up`

`sudo dhclient eth0`

**Comment by chainsx** [comment]
由于官方给的驱动问题，3b+无法使用网卡

**Comment by Qi-Sun** [comment]
等作者更新啊啊啊啊，没有网卡不方便呀

**Comment by ybeetle** [comment]
坐等 3B+

**Comment by 772366** [comment]
坐等大佬更新。

**Comment by FengGeSe** [comment]
坐等大佬更新，树莓派吃灰中

**Comment by leishiyao** [comment]
怎么办啊啊啊啊

**Comment by aiminickwong** [comment]
早已搞定，自己重新做了系统，没用这个版本。

**Comment by aiminickwong** [comment]
目前  有线无线均可使用，一切良好。

**Comment by Friday314** [comment]
楼上的，用的哪了版本？16的？

**Comment by zxsoft** [comment]
遇到了同样的问题，楼主这个ubuntu库非常好，集成了rasp-config等工具。3b+不能用太可惜了！

希望可以重视此问题，reopen这个Issue并解决。
