### ISSUE TITLE
16.04默认镜像中包内容不全

### ISSUE THREAD

**Issue by rakuten** [chainsx/ubuntu64-rpi#18]
apt-get upgrade 报很多404
apt-get install sysbench 一样报404，无法安装成功

18.04无此问题

**Comment by UMRnInside** [comment]
This is **NOT** a bug.
run `apt update` to solve 404 issue.

********
你真的不先apt update么……

**Comment by rakuten** [comment]
问题是.....我明明已经apt-get update过了.....

**Comment by chainsx** [comment]
换dns，有些dns将清华源乱解析
