### ISSUE TITLE
请问一下 3b+ 网卡问题解决了么

### ISSUE THREAD

**Issue by Virace** [chainsx/ubuntu64-rpi#22]
请问一下 3b+ 网卡问题解决了么

**Comment by leishiyao** [comment]
同关心

**Comment by chainsx** [comment]
由于各种原因，没有办法及时更新，但是方法已经出来了。
https://fedoraproject.org/wiki/Architectures/ARM/Raspberry_Pi#Wifi:

**Comment by lmxx1234567** [comment]
我基于repo主的镜像重新编译了4.18的kernel，发现可以正常使用网卡但是找不到wlan设备，经查发现是系统找不到brcm的module。重新安装modules后网卡和wifi都可以使用。
![image](https://user-images.githubusercontent.com/22516664/42621564-c30a9348-85f0-11e8-83f2-0c8f03996d64.png)
linux内核代码：https://github.com/raspberrypi/linux
