### ISSUE TITLE
缺少指令集

### ISSUE THREAD

**Issue by railjty** [chainsx/ubuntu64-rpi#24]
用的是cat /proc/cpuinfo
在arm64系统中，CPU缺少了大量在armhf系统中有指令集(如neon,还有的我不记得了)，不知为何

**Comment by chainsx** [comment]
这个我具体也不清楚什么回事，
我看过所有的rpi的arm64的系统，
/proc/cpuinfo都是一样的。

**Comment by UMRnInside** [comment]
只是指令集显示得不太一样而已……
目前已知如下对应关系：

| ARMv7 | ARM64 |
|----|----|
| neon | asimd |
| vfpv* | fp |

**Comment by railjty** [comment]
ARMv7模式下的Cortex A53 [https://raw.githubusercontent.com/railjty/openssl-patch/master/Screenshot_2018-07-19-08-15-14.png ](url)



ARMv8(ARM64)下的Cortex A53 [ https://raw.githubusercontent.com/railjty/openssl-patch/master/Screenshot_2018-07-19-08-16-10.png ](url)

**Comment by railjty** [comment]
可是有的程序比较死，只认识neon,不认识asimd(例如BoringSSL)

**Comment by railjty** [comment]
好吧，readme已经更新，另外可否发下内核编译.config以及内核image的链接？
