### ISSUE TITLE
请问未来会制作比较完整的系统吗？

### ISSUE THREAD

**Issue by wetor** [chainsx/ubuntu64-rpi#3]
关注这个项目很久了(从开机慢的15.1那时)，试了几次发现有点麻烦就换回pi64了....这个之后会考虑做比较完整的系统吗(装了就能用)？

**Comment by chainsx** [comment]
现在的唯一问题只有需要自行拓展根目录（已给出方法）

**Comment by wetor** [comment]
感谢答复！看到已经支持wifi了，过几天就刷这个！
