### ISSUE TITLE
Support rpi3-plus?

### ISSUE THREAD

**Issue by waipan** [chainsx/ubuntu64-rpi#30]
It's unable to boot from rpi3 plus.

**Comment by cx-dandelion** [comment]
Full support with ubuntu-18.04 for rpi3-plus

**Comment by waipan** [comment]
It's working now, thanks!
Can I use "apt update && apt upgrade" to update firmware?

**Comment by chainsx** [comment]
yes,but you should compile kernel by yourself to upgrade kernel.
