### ISSUE TITLE
ubuntu18.04  有防火墙吗？

### ISSUE THREAD

**Issue by zuiailaoda** [chainsx/ubuntu64-rpi#35]
安装samba  本地连不上？是防火墙原因吗

**Comment by UMRnInside** [comment]
建议:检查配置
可使用`netstat -anplut | grep 445` 或 `ss | grep 445`
以检查samba是否正常运行。

********
> chainsx: 非我也，配置也。

> iptables & ufw: 非我也，用户也。

**Comment by cx-dandelion** [comment]
形象
