### ISSUE TITLE
有错别字哦~~

### ISSUE THREAD

**Issue by lssb** [chainsx/ubuntu64-rpi#4]
开启32位支持的文档里面
`dpkg --add-architechture armel`
多了个h，应该是
`dpkg --add-architecture armel`

**Comment by chainsx** [comment]
。。。。。。

**Comment by chainsx** [comment]
这些东西没注意，。。
写这些东西太急了。

**Comment by yfgeek** [comment]
@chainsx 狂野的readme，搞笑的文风，这是一个干净利落的树莓派爱好者，粉了！
