### ISSUE TITLE
测试版并不能自动扩展分区

### ISSUE THREAD

**Issue by ddqp** [chainsx/ubuntu64-rpi#6]
安装后，查看并没有自动扩展，而且，使用ext4的扩展方法，仍然无法生效。

还是用回稳定版了。

**Comment by chainsx** [comment]
那不然怎么叫测试版。

**Comment by chainsx** [comment]
这个问题正在解决

**Comment by ddqp** [comment]
不知道你用docker吗，是docker用起来有问题，container经常无法启动，不停的restarting

**Comment by chainsx** [comment]
容器的话，我会满满完善的。
