### ISSUE TITLE
Swapfile is unavailable on BTRFS

### ISSUE THREAD

**Issue by UMRnInside** [chainsx/ubuntu64-rpi#7]
I followed [this instruction](https://github.com/chainsx/ubuntu64-rpi/blob/ubuntu-16.04.3-arm64/Documentation/add-swap.md)

But I failed. When I tried to `swapon /swapfile`, it reported:
`swapon: /swapfile: swapon failed: Invalid argument`

It is said that using swapfile on _Copy-on-Write_ filesystems is a bad idea.

********

即使按照该文档的指示，我也无法启用`swapfile`

据说在 _写时复制_ 文件系统上使用swapfile是个 _馊主意_

**Comment by dyxang** [comment]
你可以试一试这个
You can look this http://www.bitpi.co/2015/02/11/how-to-change-raspberry-pis-swapfile-size-on-rasbian/
This is a demonstration on raspbian.
----

中文请看这里
http://shumeipai.nxez.com/2017/12/18/how-to-modify-raspberry-pi-swap-partition.html

**Comment by cx-dandelion** [comment]
的确是个馊主意

**Comment by chainsx** [comment]
我已经改过来了
